import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Nav from "@/components/Nav";
import BookProvider from "@/contexts/BookProvider";
// import bgImage from "@/images/EXPORTBG.png"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
    <BookProvider>
      <Nav />
      <main className="">
        {children}
      </main>
    </BookProvider>
    </>
  );
}
