import { Geist, Geist_Mono } from "next/font/google";
// import bgImage from "@/images/EXPORT-BG.png"
import "@/app/globals.css";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>       
        <main className="">
          {children}
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
