import { Geist, Geist_Mono } from "next/font/google";
import bgImage from "@/images/EXPORTBG.png"
import authImage from "@/images/auth-illustration.png"
import "@/app/globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
        <main className="flex items-start justify-center min-h-dvh">
          <div className='bg m-0 w-full md:w-[60%] lg:w-1/2  flex items-center justify-center p-4 sm:p-8 xl:p-12'>
            {children}
          </div> 
          <div className='md:block hidden m-0 md:w-[40%] lg:w-1/2'>
            <Image src={authImage} alt="auth-illustration" className='w-full md:min-h-[800px] lg:min-h-dvh' />
          </div>

        </main>
 
  );
}
